### ISSUE TITLE
Plugin randomly crashes the server due to an "Error while Ticking"

### ISSUE THREAD

**Issue by Budderman18** [Plugily-Projects/TheBridge#28]
At random moments when playing on other worlds, Bridges randomly causes the server to crash.
Error:
[18:20:02] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception while ticking
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1312) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at plugily.projects.thebridge.utils.ExceptionLogHandler.publish(ExceptionLogHandler.java:68) ~[?:?]
        at java.util.logging.Logger.log(Logger.java:979) ~[?:?]
        at java.util.logging.Logger.doLog(Logger.java:1006) ~[?:?]
        at java.util.logging.Logger.log(Logger.java:1117) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:604) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:147) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:492) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.world.level.material.Fluid.a(SourceFile:76) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:746) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.world.level.TickListServer.b(TickListServer.java:89) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:439) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1299) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        ... 5 more
[18:20:02] [Server thread/ERROR]:       Cause of unexpected exception was
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at plugily.projects.thebridge.utils.ExceptionLogHandler.publish(ExceptionLogHandler.java:68) ~[?:?]
        at java.util.logging.Logger.log(Logger.java:979) ~[?:?]
        at java.util.logging.Logger.doLog(Logger.java:1006) ~[?:?]
        at java.util.logging.Logger.log(Logger.java:1117) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:604) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:147) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:492) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.world.level.material.Fluid.a(SourceFile:76) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:746) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.world.level.TickListServer.b(TickListServer.java:89) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:439) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1299) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Tigerpanzer02** [comment]
> At random moments when playing on other worlds, Bridges randomly causes the server to crash.
> Error:
> [18:20:02] [Server thread/ERROR]: Encountered an unexpected exception
> net.minecraft.ReportedException: Exception while ticking
> at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1312) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at java.lang.Thread.run(Thread.java:831) [?:?]
> Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
> at plugily.projects.thebridge.utils.ExceptionLogHandler.publish(ExceptionLogHandler.java:68) ~[?:?]
> at java.util.logging.Logger.log(Logger.java:979) ~[?:?]
> at java.util.logging.Logger.doLog(Logger.java:1006) ~[?:?]
> at java.util.logging.Logger.log(Logger.java:1117) ~[?:?]
> at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:604) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:147) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:492) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.world.level.material.Fluid.a(SourceFile:76) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.level.WorldServer.a(WorldServer.java:746) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.world.level.TickListServer.b(TickListServer.java:89) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:439) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1299) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> ... 5 more
> [18:20:02] [Server thread/ERROR]: Cause of unexpected exception was
> java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
> at plugily.projects.thebridge.utils.ExceptionLogHandler.publish(ExceptionLogHandler.java:68) ~[?:?]
> at java.util.logging.Logger.log(Logger.java:979) ~[?:?]
> at java.util.logging.Logger.doLog(Logger.java:1006) ~[?:?]
> at java.util.logging.Logger.log(Logger.java:1117) ~[?:?]
> at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:604) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:147) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:492) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.world.level.material.Fluid.a(SourceFile:76) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.level.WorldServer.a(WorldServer.java:746) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.world.level.TickListServer.b(TickListServer.java:89) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:439) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1299) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
> at java.lang.Thread.run(Thread.java:831) [?:?]

Please join our discord to give you support. https://discord.plugily.xyz
